---
name: 02 Azure Landing Zones Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skipWhatIf:
        description: 'Skip What If Check?'
        default: false
        type: boolean
      managementgroups:
        description: 'Run Steps: Management Groups'
        type: boolean
        default: true
      loggingandsentinel:
        description: 'Run Steps: Logging and Sentinel'
        type: boolean
        default: true
      policydefinitions:
        description: 'Run Steps: Policy Definitions'
        type: boolean
        default: true
      roledefinitions:
        description: 'Run Steps: Role Definitions'
        type: boolean
        default: true
      policyassignments:
        description: 'Run Steps: Policy Assignments'
        type: boolean
        default: true
      managementgroupdiagnosticsettings:
        description: 'Run Steps: Management Group Diagnostic Settings'
        type: boolean
        default: true
      subscriptionplacement:
        description: 'Run Steps: Subscription Placement'
        type: boolean
        default: true
      connectivity:
        description: 'Run Steps: Connectivity'
        type: boolean
        default: true
      destroy:
        description: '[DANGER!] Destroy? [DANGER!]'
        default: false
        type: boolean

jobs:
  plan_and_apply:
    uses: jared-holgate-microsoft-demos/alzbg-mgmt-templates/.github/workflows/cd-template.yaml@main
    name: 'CD'
    permissions:
      id-token: write
      contents: read
    with:
      skipWhatIf: ${{ contains(inputs.skipWhatIf, 'true') }}
      destroy: ${{ inputs.destroy }}
      managementgroups: ${{ inputs.managementgroups }}
      loggingandsentinelresourcegroup: ${{ inputs.loggingandsentinel }}
      loggingandsentinel: ${{ inputs.loggingandsentinel }}
      custompolicydefinitions: ${{ inputs.policydefinitions }}
      customroledefinitions: ${{ inputs.roledefinitions }}
      managementgroupdiagnosticsettings: ${{ inputs.managementgroupdiagnosticsettings }}
      policyassignments: ${{ inputs.policyassignments }}
      workloadspecificpolicyassignments: ${{ inputs.policyassignments }}
      subscriptionplacement: ${{ inputs.subscriptionplacement }}
      connectivityresourcegroup: ${{ inputs.connectivity }}
      hubandspoke: ${{ inputs.connectivity }}

